sudo: false
language: node_js
cache:
  directories:
    - node_modules
notifications:
  email: false
node_js:
  - '4.2.2'
before_install:
  - npm i -g npm@^2.0.0
before_script:
  - npm prune
script:
  - git --version
  - echo sorted tags using "sort command"
  - git for-each-ref --format='%(*committerdate:raw)%(committerdate:raw) %(refname)' refs/tags | sort -n
  - echo sorted tags using "--sort argument"
  - git tag --sort version:refname
  - npm test
after_success:
  - npm run semantic-release
branches:
  except:
    - "/^v\\d+\\.\\d+\\.\\d+$/"
